using UnityEngine;

namespace MTAssets.NativeAndroidToolkit
{
    /*
    * This script was generated by Native Android Toolkit Preferences and informs
    * if the NAT Camera can be safe initialized.
    */

    [AddComponentMenu("")] //Hide this script in component menu.
    public class CameraInitialization
    {
        public static bool isSafeToInitializeCamera = false;
        public static string productNameThatGeneratedThisScript = "Projeto MT Assets";
    }
}